services:
  app:
    container_name: app_container
    image: feliperd/crud-app:1.0
    networks:
      - app_network
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: product
    networks:
      - app_network
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
